package config

const (
	PORT                = "PORT"
	DB_URL              = "DB_URL"
	MIGRATIONS_DIR      = "MIGRATIONS_DIR"
	MIN_AVG_DWELL_MS    = "MIN_AVG_DWELL_MS"
	MIN_SINGLE_DWELL_MS = "MIN_SINGLE_DWELL_MS"
	DWELL_WINDOW        = "DWELL_WINDOW"
	MAX_DAILY_LESSONS   = "MAX_DAILY_LESSONS"
	DATASET_SCALE          = "DATASET_SCALE"
	DATASET_SEED           = "DATASET_SEED"
	DB_MAX_OPEN_CONNS      = "DB_MAX_OPEN_CONNS"
	DB_MAX_IDLE_CONNS      = "DB_MAX_IDLE_CONNS"
	DB_CONN_MAX_LIFETIME_S = "DB_CONN_MAX_LIFETIME_S"
	DB_CONN_MAX_IDLE_S     = "DB_CONN_MAX_IDLE_S"
)
